Fix travis to example
https://gist.github.com/maelvalais/068af21911c7debc4655cdaa41bbf092

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,46 +1,159 @@
+# Inspired from the .travis.yml in
+# https://github.com/davidchall/homebrew-hep/
+
+# This script can be executed in three different modes:
+# - cron/api (api is when you select 'trigger build' in travis): in this mode,
+#   all the formulas are tested to make sure that there is no shared lib
+#   breakage
+# - push to master: does nothing
+# - pull-request: in this mode, the updated formulas are built and bottled
+#   and the bottles are pushed to bintray as 'unpublished'. The DSL commit
+#   is pushed as a tag, e.g., 'pr-1234', which us unrelated to master.
+
 language: ruby
-rvm: system
+if: tag IS blank AND NOT type IN (push)
+env:
+  global:
+    - HOMEBREW_LOGS=/tmp # Prevent ~/.cache/Homebrew/Logs from being rebuilt
+    - HOMEBREW_NO_AUTO_UPDATE=yes # Prevents redundant auto-updates from brew
+
+    ###### Bintray configuration ######
+    - TAP_BOTTLE_ORG=touist                # Used in this script only
+    - TAP_BOTTLE_ROOT_URL=https://dl.bintray.com/$TAP_BOTTLE_ORG/bottles-touist
+    - HOMEBREW_BINTRAY_USER=maelvalais
+    # HOMEBREW_BINTRAY_KEY                 # Secret variable set in Travis CI
+
+    ###### AWS S3 configuration ######
+    - AWS_REGION=eu-west-1                 # aws-sdk-s3 gem errors without it
+    - BUCKET=homebrew-touist-travis
+    # AWS_ACCESS_KEY_ID                    # Secret variable set in Travis CI
+    # AWS_SECRET_ACCESS_KEY                # Secret variable set in Travis CI
+
+    ###### Github configuration ######
+    # This config allows test-bot to push tags (eg. pr-1234) and DSL commits.
+    # They will be pushed to github.com/$GITHUB_USER/homebrew-%TAP%.
+    - GITHUB_USER=touist
+    # GITHUB_TOKEN                   # (Secret) For pushing bottle DSL commits
+
+# (1) remember to use 'brew cleanup -s' at the end of the travis script;
+# otherwise, the $HOME/Library/Caches/Homebrew folder will be enormous
+# (~2GB for the 4 jobs). This is because this folder is already present on
+# osx images and it is big.
+# (2) For a time, I had removed $HOME/.cache/Homebrew (cache of Linuxbrew)
+# because it was also storing some logs in $HOME/.cache/Homebrew/Logs, making
+# the cache rebuilt every time.
 cache:
   directories:
-    - $HOME/.gem/ruby
-    - Library/Homebrew/vendor/bundle
+    - "$HOME/.cache/pip"
+    - "$HOME/.gem/ruby"
+    - "$HOME/Library/Caches/Homebrew" # (1)
+    - "$HOME/.cache/Homebrew"         # (2)
 
-# https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
-os: osx
-matrix:
-  include:
-    - osx_image: xcode10.1
-      env: OSX=10.13
-    - osx_image: xcode9.1
-      env: OSX=10.12
-    - osx_image: xcode8
-      env: OSX=10.11
+install:
+  # the official test-bot won't let you run inside TravisCI, so we use
+  # davidchall's one. David's test-bot cannot push the commit using
+  # Oauth github + https (only ssh) so I use my own.
+  - brew tap maelvalais/test-bot
+  # Often, Travis CI image's git is too old for brew
+  - brew install git
+  # Install the ruby AWS gem so that I can upload bottles to S3
+  - rvm default do gem install aws-sdk-s3
+  # IMPORTANT STEP: link the tap inside brew to our current travis-cloned tap
+  # Step: 1) create the intermediate folders <user>/<repo> so that
+  # we can 2) remove <repo> and 3) replace it with a sym link
+  # that will point to the travis build folder.
+  # If we don't do that, the tap be cloned using the default master
+  # branch, and thus we cannot test our tap at the current pushed commit.
+  # We also need to unshallow in 4) because sometimes travis does not
+  # clone thouroughly but we need a deep clone.
+  - mkdir -p $(brew --repo $TRAVIS_REPO_SLUG)   # 1)
+  - rm -rf $(brew --repo $TRAVIS_REPO_SLUG)     # 2)
+  - ln -s $PWD $(brew --repo $TRAVIS_REPO_SLUG) # 3)
+  - git fetch --unshallow || true               # 4)
+  # Unless I am in 'brew test-bot', I don't want to fail on warnings.
+  # perl regex: needed so that I can use 1.4.0-beta1 or 1.4.0-rc1 as stable versions
+  - perl -pi -e 's/(.*)problem(.*version.*should not contain.*)$/$1opoo$2/' $(brew --repo)/Library/Homebrew/dev-cmd/audit.rb
+  - git -C $(brew --repo) commit -a -m "disable error on beta or alpha version"
 
-before_install:
-  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
-  - if [ -f ".git/shallow" ]; then
-      travis_retry git fetch --unshallow;
-    fi
-  - HOMEBREW_REPOSITORY="$(brew --repo)"
-  - sudo chown -R "$USER" "$HOMEBREW_REPOSITORY"
-  - git -C "$HOMEBREW_REPOSITORY" reset --hard origin/master
-  - brew update || brew update
-  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
-  - mkdir -p "$HOMEBREW_TAP_DIR"
-  - rm -rf "$HOMEBREW_TAP_DIR"
-  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
-  - export HOMEBREW_DEVELOPER="1"
-  - ulimit -n 1024
-
+# WARNING: I discovered that 'set -e' is breaking Travis CI. I was using for
+# stopping a multiple-lines command as soon as one of the commands fails.
+# After having 'set -e', internal travis commands may stop working, e.g.:
+#   /Users/travis/.travis/job_stages: line 57: shell_session_update: command not found
+# is an internal error that shouldn't stop the script for continuing, but
+# because of 'set -e', the whole internal Travis CI script stops.
+# Conclusion: avoid using 'set -e' and more generally avoid for-loops and
+# multi-line commands that should fail when one of the commands fails.
 script:
-  - brew tap davidchall/test-bot
-  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
-      brew test-bot --ci-testing;
-    else
-      brew test-bot --ci-pr;
+  - |
+    if [[ $TRAVIS_EVENT_TYPE =~ cron|api ]]; then
+      brew install *.rb && brew test *.rb && brew linkage --test *.rb || exit 123
     fi
+  - if [[ $TRAVIS_EVENT_TYPE =~ pull_request ]]; then brew test-bot --root-url=$TAP_BOTTLE_ROOT_URL; fi
+  - ls *.bottle*.* || echo "==> No bottle created here"
 
-notifications:
-  email:
-    on_success: never
-    on_failure: always
+jobs:
+  include:
+    - &run-osx
+      os: osx
+      osx_image: xcode9.4
+      env: OS=high_sierra-10.13
+      # We must use 'rvm: system' because the system ruby doesn't rely on
+      # Homebrew, which allows us to reinstall Homebrew without having a
+      # damaged ruby. We need ruby because we use the 'aws-sdk-s3' gem.
+      rvm: system
+      before_install: # IMPORTANT: HOMEBREW_DEVELOPER must not be set here.
+        # First we uninstall any outdated versions of xquartz; otherwise,
+        # Homebrew will complain of of older version (2.9.7) being outdated
+        # even though we install a new version. Remember that
+        # /usr/local/Caskroom will also be deleted below.
+        - brew cask outdated xquartz || brew cask uninstall xquartz
+        # Three reasons not to use the /usr/local and Homebrew installations
+        # that come in the Travis CI images:
+        # 1) because Travis CI has installed many non-homebrew things into
+        #    /usr/local that randomly cause 'brew doctor' to fail;
+        # 2) after time, the osx image contains an outdated Homebrew that
+        #    has weird 'unlinked kegs' and such;
+        # 3) also because it takes a long time to 'brew update' from an old
+        #    Homebrew anyway, so why not start fresh.
+        - mkdir ~/usr_local && sudo mv /usr/local/* ~/usr_local
+        - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+
+        # Either xquartz was already installed at its latest version or it has
+        # been uninstalled. First, we put the cask back in place if it has not
+        # been uninstalled.
+        - |
+          if [ -d ~/usr_local/Caskroom/xquartz ];
+          then sudo mv ~/usr_local/Caskroom /usr/local/Caskroom;
+          else travis_retry brew cask install xquartz --no-quarantine; fi
+        # We still need the Homebrew ruby on macOS 10.12 and 10.11 because the
+        # system ruby uses an old openssl version ("tlsv1 alert protocol").
+        - travis_retry brew install libyaml gmp openssl@1.1 openssl
+    # TO BE ENABLED AS SOON AS TRAVIS HAS A MOJAVE IMAGE:
+    #- <<: *run-osx
+    #  os: osx
+    #  osx_image: xcode9.4
+    #  env: OS=high_sierra-10.13
+
+    - <<: *run-osx
+      os: osx
+      osx_image: xcode9.2
+      env: OS=sierra-10.12
+
+after_script:
+  # In case the AWS_SECRET_ACCESS_KEY and AWS_SECRET_ACCESS_KEY are not
+  # available, we don't want the build to fail.
+  # Here, the 'testing' jobs have finished and must upload their *.{json,tar.gz}
+  - |
+    rvm default do ruby <<EOF || true
+    require 'aws-sdk-s3'; s3 = Aws::S3::Resource.new
+    Dir["*.{json,tar.gz}"].each { |f| s3.bucket("$BUCKET").put_object(key:"$TRAVIS_BUILD_NUMBER/#{f}").upload_file(f) }
+
+before_cache:
+  # Scrub cache so that travis only caches stuff for installed formulae.
+  - brew cleanup -s
+  - brew cask cleanup
+  # Remove temporary stuff (idk why they put that in ~/.cache... that should be in /tmp)
+  - rm -f ~/Library/Caches/Homebrew/linkage.db ~/.cache/Homebrew/linkage.db
+  # List the formulae so that I understand why the cache is huge sometimes
+  - brew list
+  - du -h ~/Library/Caches/Homebrew || du -h ~/.cache/Homebrew/linkage.db
